#Copyright (c) 2021 Cisco and/or its affiliates.
#
#This software is licensed to you under the terms of the Cisco Sample
#Code License, Version 1.1 (the "License"). You may obtain a copy of the
#License at
#
#               https://developer.cisco.com/docs/licenses
#
#All use of the material herein must be in accordance with the terms of
#the License. All rights not expressly granted by the License are
#reserved. Unless required by applicable law or agreed to separately in
#writing, software distributed under the License is distributed on an "AS
#IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
#or implied.

# Following Values need to be manually changed or changed to a variable
#                          "ip": "xxxxxx",
#                          "srcIpPrefix": "xxxxxx",
#                          "tDn": "xxxxxxx",
#

### This Playbook creates a Tenant Span for a given endpoint
- name: Play 1 Create Span for source IP
  hosts: all
  gather_facts: no


  tasks:
#### ACI Login Fact
   - set_fact:
      aci_login: &aci_login
        host: "{{ inventory_hostname }}"
        username: "{{ lookup('env', 'ANSIBLE_NET_USERNAME') }}"
        password: "{{ lookup('env', 'ANSIBLE_NET_PASSWORD') }}"
        use_ssl: yes
        validate_certs: no

#### Add SPAN Destination Group based on tenant_name 
#### Some stuff is hardcoded for lab purposes needs to be exchanged 
   - name: Add Destination Group
     aci_rest:
       <<: *aci_login
       path: /api/node/mo/uni/tn-{{ tenant_name }}/destgrp-span_dest.json
       method: post
       content:
           {
        "totalCount": "1",
        "imdata": [
            {
                "spanDestGrp": {
                    "attributes": {
                        "annotation": "",
                        "descr": "",
                        "dn": "uni/tn-{{ tenant_name }}/destgrp-span_dest",
                        "name": "span_dest",
                        "nameAlias": "",
                        "ownerKey": "",
                        "ownerTag": ""
                    },
                    "children": [
                        {
                            "spanDest": {
                                "attributes": {
                                    "annotation": "",
                                    "descr": "",
                                    "name": "span_dest",
                                    "nameAlias": "",
                                    "ownerKey": "",
                                    "ownerTag": ""
                                },
                                "children": [
                                    {
                                        "spanRsDestEpg": {
                                            "attributes": {
                                                "annotation": "",
                                                "dscp": "unspecified",
                                                "finalIp": "0.0.0.0",
                                                "flowId": "1",
                                                "ip": "xxxxxx",
                                                "mtu": "1518",
                                                "srcIpPrefix": "xxxxxx",
                                                "tDn": "xxxxxxx",
                                                "ttl": "64",
                                                "ver": "ver2",
                                                "verEnforced": "no"
                                            }
                                        }
                                    }
                                ]
                            }
                        }
                    ]
                }
            }
        ]
    }
     delegate_to: localhost



#### Add Span Source Group
   - name: Add Source Group
     aci_rest:
       <<: *aci_login
       path: /api/mo/uni/tn-{{ tenant_name }}/srcgrp-span_src.json
       method: post
       content:
           {
               "totalCount": "1",
               "imdata": [
                   {
                       "spanSrcGrp": {
                           "attributes": {
                               "adminSt": "enabled",
                               "annotation": "",
                               "descr": "",
                               "dn": "uni/tn-{{ tenant_name }}/srcgrp-span_src",
                               "name": "span_src",
                               "nameAlias": "",
                               "ownerKey": "",
                               "ownerTag": ""
                           },
                           "children": [
                               {
                                   "spanSrc": {
                                       "attributes": {
                                           "annotation": "",
                                           "descr": "",
                                           "dir": "both",
                                           "name": "span_src",
                                           "nameAlias": "",
                                           "ownerKey": "",
                                           "ownerTag": "",
                                           "spanOnDrop": "no"
                                       },
                                       "children": [
                                           {
                                               "spanRsSrcToEpg": {
                                                   "attributes": {
                                                       "annotation": "",
                                                       "tDn": "uni/tn-{{ tenant_name }}/ap-{{ ap_name }}/epg-{{ epg_name }}"
                                                   }
                                               }
                                           }
                                       ]
                                   }
                               },
                               {
                                   "spanSpanLbl": {
                                       "attributes": {
                                           "annotation": "",
                                           "descr": "",
                                           "name": "span_dest",
                                           "nameAlias": "",
                                           "ownerKey": "",
                                           "ownerTag": "",
                                           "tag": "yellow-green"
                                       }
                                   }
                               }
                           ]
                       }
                   }
               ]
           }
     delegate_to: localhost



#### Set TicketText
   - name: Set Ticket Stat
     set_stats:
       data:
         ticketText: "RSPAN Session Created on xxxxxxxx"
       per_host: no