#Copyright (c) 2021 Cisco and/or its affiliates.
#
#This software is licensed to you under the terms of the Cisco Sample
#Code License, Version 1.1 (the "License"). You may obtain a copy of the
#License at
#
#               https://developer.cisco.com/docs/licenses
#
#All use of the material herein must be in accordance with the terms of
#the License. All rights not expressly granted by the License are
#reserved. Unless required by applicable law or agreed to separately in
#writing, software distributed under the License is distributed on an "AS
#IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
#or implied.


### This Playbook creates the Flow Analysis in Cisco Network Insights


- name: Play 1 Login to ND
  hosts: all
  connection: local


  tasks:

### ND Login
    - name: Login 
      uri:
          url: https://{{ nd }}/login
          headers:
            {
             Content-Type: "application/json"
            }
          method: POST
          body_format: json
          body:
            {
             username: "{{ lookup('env', 'ANSIBLE_NET_USERNAME') }}",
             password: "{{ lookup('env', 'ANSIBLE_NET_PASSWORD') }}",
             domain: "DefaultAuth"
            }
          status_code: 200
          return_content: yes
          validate_certs: no
      register: qResult

    - set_fact:
        ndCookie: "{{ qResult.cookies.AuthCookie }}"
        authCookie: "{{ qResult.set_cookie }}"

### Create flow record Policy based on endpoint DN 
    - name: Create Flow Record Policy
      uri:
          url: https://{{ nd }}/sedgeapi/v1/cisco-nir/api/api/telemetry/config/policy.json?fabricName={{ siteName }}
          headers:
            {
             Content-Type: "application/json",
             AuthCookie: "{{ ndCookie }}",
             Cookie: "{{ authCookie }}"
            }
          method: POST
          body_format: json
          body:
             {
                 "method": "POST",
                 "uri": "/api/node/mo/uni/tn-{{ tenant_name }}/ctx-{{ tenant_name }}_VRF.json",
                 "payload": {
                     "telemetrySubnetFltGrp": {
                         "attributes": {
                             "name": "Issue{{ issueID }}"
                         },
                         "children": [
                             {
                                 "telemetrySubnetFilter": {
                                     "attributes": {
                                         "subnetIp": "{{ endpoint }}/32"
                                     }
                                 }
                             }
                         ]
                     }
                 }
             }
          status_code: 200
          return_content: yes
          validate_certs: no
      register: qResult


#### Set TicketText
    - name: Set Ticket Stat
      set_stats:
        data:
          ticketText: "NetworkInsights FlowAnalysis Created"
        per_host: no