#Copyright (c) 2021 Cisco and/or its affiliates.
#
#This software is licensed to you under the terms of the Cisco Sample
#Code License, Version 1.1 (the "License"). You may obtain a copy of the
#License at
#
#               https://developer.cisco.com/docs/licenses
#
#All use of the material herein must be in accordance with the terms of
#the License. All rights not expressly granted by the License are
#reserved. Unless required by applicable law or agreed to separately in
#writing, software distributed under the License is distributed on an "AS
#IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
#or implied.


# This Playbook collects the overall SmartEvent count and sets a TicketText based on this


- name: Play 1 Login to CNAE
  hosts: all
  connection: local


  tasks:
  #### NAE Login Step 1
    - name: WHOAMI
      uri:
          url: https://{{ nd }}/nae/api/v1/whoami
          method: GET
          status_code: 200
          return_content: yes
          validate_certs: no
      register: output

    - set_fact:
        token: "{{ output.x_nae_login_otp }}"
        cookie: "{{ output.set_cookie }}"

#### NAE Login Step 3
    - name: Login Step 2
      uri:
          url: https://{{ nd }}/nae/api/v1/login 
          headers:
            {
             Cookie: "{{ cookie }}", 
             X-NAE-LOGIN-OTP: "{{ token }}",

             domain : "Local",
             Content-Type: "application/json"
            }
          method: POST
          body_format: json
          body:
            {
             username: "{{ lookup('env', 'ANSIBLE_NET_USERNAME') }}",
             password: "{{ lookup('env', 'ANSIBLE_NET_PASSWORD') }}",
            }
          status_code: 200
          return_content: yes
          validate_certs: no
      register: result



    - set_fact:
          cnaelogin: "{{ result.x_nae_csrf_token }}"
          cnaecookie: "{{ result.set_cookie }}"

#### Get Latest NAE Epoch        
  
    - name: Get NAE Latest EPOCH 
      uri:
          url: https://{{ nd }}/nae/api/v1/event-services/epochs?$status=FINISHED&$sort=-collection_time&$size=1&$processed=true&$page=0
          headers:
            {
             x_nae_csrf_token: "{{ cnaelogin }}",
             Cookie: "{{ cnaecookie }}",
             Content-Type: "application/json",
             Accept: "application/json"
            }
          method: GET
          status_code: 200
          return_content: yes
          validate_certs: no
      register: qResult
      delegate_to: localhost
    
#### Set fact for TicketText

    - name: Set fact for processing of JSON
      set_fact: 
          eventInfoCount: "{{ qResult.json.value.data[0].event_info[0].count | default('0') }}"
          eventCriticalCount: "{{ qResult.json.value.data[0].event_info[1].count | default('0') }}"
          eventMajorCount: "{{ qResult.json.value.data[0].event_info[2].count | default('0') }}"
          eventMinorCount: "{{ qResult.json.value.data[0].event_info[3].count | default('0') }}"
          eventWarningCount: "{{ qResult.json.value.data[0].event_info[4].count | default('0') }}"

#### Set TicketText
    - name: Set Ticket Stat
      set_stats:
        data:
          ticketText: "NAE Eventcount   <br>   <br>Critical Events: {{ eventCriticalCount }}   <br>Major Events: {{ eventMajorCount }}   <br>Minor Events: {{ eventMinorCount }}   <br>Warning Events: {{ eventWarningCount }}   <br>Info Events: {{ eventInfoCount }}   <br>"
        per_host: no
     