#Copyright (c) 2021 Cisco and/or its affiliates.
#
#This software is licensed to you under the terms of the Cisco Sample
#Code License, Version 1.1 (the "License"). You may obtain a copy of the
#License at
#
#               https://developer.cisco.com/docs/licenses
#
#All use of the material herein must be in accordance with the terms of
#the License. All rights not expressly granted by the License are
#reserved. Unless required by applicable law or agreed to separately in
#writing, software distributed under the License is distributed on an "AS
#IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
#or implied.





### This Playbooks queries all compute Ressources from Intersight



- name: Play 1 Query Intersight
  hosts: all
  connection: local
  gather_facts: no



  vars:
    # Create an anchor for api_info that can be used throughout the file
    api_info: &api_info
      api_private_key: "/opt/intersight.pem"
      api_key_id: "{{ intersightapitoken }}"

  tasks:
    # Get detailed inventory (similar to what is shown in the Inventory menu in the UI)
    - intersight_rest_api:
        <<: *api_info
        resource_path: "/virtualization/VmwareVirtualMachines"
        query_params:
          $filter: "IpAddress eq '{{ endpoint }}'"
        # Return the full API Results list
      register: qResult
      delegate_to: localhost

    - name: Set VM Variables
      set_fact:
        vmName: "{{ qResult.api_response.GuestInfo.Hostname }}"
        vmOs: "{{ qResult.api_response.GuestInfo.OperatingSystem | urlencode }}"
        vmMemCap: "{{ qResult.api_response.MemoryCapacity.Capacity }}"
        vmMemUsed: "{{ qResult.api_response.MemoryCapacity.Used }}"
        vmMemFree: "{{ qResult.api_response.MemoryCapacity.Free }}"
        vmPowerState: "{{ qResult.api_response.PowerState }}"
        vmCpuCap: "{{ qResult.api_response.ProcessorCapacity.Capacity }}"
        vmCpuUsed: "{{ qResult.api_response.ProcessorCapacity.Used }}"
        vmCpuFree: "{{ qResult.api_response.ProcessorCapacity.Free }}"

    - name: Set Host ID Variable
      set_fact:
         hostId: "{{ qResult.api_response.Ancestors[0].link | regex_search('(?<=Hosts/)(.*)') }}"

    - intersight_rest_api:
        <<: *api_info
        resource_path: /virtualization/VmwareHosts
        query_params:
          $filter: "Moid eq '{{ hostId }}'"
        # Return the full API Results list
      register: qResult
      delegate_to: localhost


    - name: Set Host Name Variable
      set_fact:
         hostName: "{{ qResult.api_response.Name }}"

    - debug:
        var: hostName

    - name: Set Ticket Stat
      set_stats:
        data:
          ticketText: "Intersight Data<br><br>VM Name: {{ vmName }}   <br>ESXI Host: {{ hostName }}   <br>Power State: {{ vmPowerState }}   <br>VM Memory Capacity: {{ vmMemCap }}   <br>VM Memory Used: {{ vmMemUsed }}   <br>VM Memory Free: {{ vmMemFree }}   <br>VM CPU Capacity: {{ vmCpuCap }}   <br>VM CPU Used: {{ vmCpuUsed }}   <br>VM CPU Free: {{ vmCpuFree }}   <br>"
        per_host: no
     